#POST https://fullstack-osa3-puhelinluettelo.onrender.com/api/persons
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Testi Jannu",
    "number": "11-111111"
}